-- Script de Migración para el Inventario de Masas (Pastelería y Panadería)
-- Ejecutar este script en el SQL Editor de Supabase (https://supabase.com/dashboard)

-- 1. Crear tabla de inventario de masas
CREATE TABLE IF NOT EXISTS inventario_masas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    stock_actual NUMERIC NOT NULL DEFAULT 0,
    unidad_medida TEXT NOT NULL DEFAULT 'kg',
    stock_minimo NUMERIC NOT NULL DEFAULT 0,
    costo_unitario NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crear tabla de movimientos de masas
CREATE TABLE IF NOT EXISTS movimientos_masas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    masa_id BIGINT REFERENCES inventario_masas(id) ON DELETE CASCADE,
    tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),
    cantidad NUMERIC NOT NULL,
    motivo TEXT,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    creado_por TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Desactivar RLS para permitir accesos libres desde la app cliente
ALTER TABLE inventario_masas DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_masas DISABLE ROW LEVEL SECURITY;

-- 4. Insertar datos iniciales semilla
INSERT INTO inventario_masas (nombre, stock_actual, unidad_medida, stock_minimo, costo_unitario)
VALUES 
('Masa de Croissant', 5.0, 'kg', 2.0, 15.50),
('Masa de Pan de Chocolate', 4.0, 'kg', 1.5, 18.00),
('Masa Brioche', 3.0, 'kg', 1.0, 12.00),
('Masa de Hojaldre', 6.0, 'kg', 2.0, 14.50),
('Masa Madre', 2.5, 'kg', 0.5, 8.00)
ON CONFLICT (nombre) 
DO UPDATE SET
    unidad_medida = EXCLUDED.unidad_medida,
    stock_minimo = EXCLUDED.stock_minimo,
    costo_unitario = EXCLUDED.costo_unitario;

-- 5. Recargar el caché de esquemas de PostgREST
NOTIFY pgrst, 'reload schema';
