-- ================================================================
-- Migración consolidada pendiente para el proyecto de Supabase actual
-- (recpbqwsjbmcairosqny). Ejecutar completo en el SQL Editor de Supabase.
-- Cubre: user_migration.sql + open_accounts_migration.sql + masas_migration.sql
-- ================================================================

-- 1. USUARIOS --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Contraseña del usuario (texto plano para facilidad de uso local)
    role TEXT NOT NULL CHECK (role IN ('admin', 'cajero', 'otro')),
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

INSERT INTO usuarios (username, password, role, nombre)
VALUES
('admin', 'admin123', 'admin', 'Administrador Yanaloma'),
('cajero', 'cajero123', 'cajero', 'Cajero de Turno')
ON CONFLICT (username)
DO UPDATE SET
    nombre = EXCLUDED.nombre,
    role = EXCLUDED.role,
    password = EXCLUDED.password;

-- 2. CUENTAS ABIERTAS (columna 'estado' en transacciones) ------------------
-- Sin esto, procesarVenta() falla al insertar porque la columna no existe.
ALTER TABLE transacciones
ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'PAGADA' CHECK (estado IN ('PAGADA', 'PENDIENTE'));

COMMENT ON COLUMN transacciones.estado IS 'Estado de la transacción: PAGADA (Finalizada y contabilizada) o PENDIENTE (Cuenta abierta acumulando consumos)';

-- 3. PASTELERÍA Y PANADERÍA (masas) -----------------------------------------
CREATE TABLE IF NOT EXISTS inventario_masas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT UNIQUE NOT NULL,
    stock_actual NUMERIC NOT NULL DEFAULT 0,
    unidad_medida TEXT NOT NULL DEFAULT 'kg',
    stock_minimo NUMERIC NOT NULL DEFAULT 0,
    costo_unitario NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS movimientos_masas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    masa_id BIGINT REFERENCES inventario_masas(id) ON DELETE CASCADE,
    tipo_movimiento TEXT NOT NULL CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA')),
    cantidad NUMERIC NOT NULL,
    motivo TEXT,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    creado_por TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE inventario_masas DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos_masas DISABLE ROW LEVEL SECURITY;

INSERT INTO inventario_masas (nombre, stock_actual, unidad_medida, stock_minimo, costo_unitario)
VALUES
('Masa de Croissant', 5.0, 'kg', 2.0, 15.50),
('Masa de Pan de Chocolate', 4.0, 'kg', 1.5, 18.00),
('Masa Brioche', 3.0, 'kg', 1.0, 12.00),
('Masa de Hojaldre', 6.0, 'kg', 2.0, 14.50),
('Masa Madre', 2.5, 'kg', 0.5, 8.00)
ON CONFLICT (nombre)
DO UPDATE SET
    unidad_medida = EXCLUDED.unidad_medida,
    stock_minimo = EXCLUDED.stock_minimo,
    costo_unitario = EXCLUDED.costo_unitario;

-- 4. Recargar el caché de esquemas de PostgREST -----------------------------
NOTIFY pgrst, 'reload schema';
