-- Script de Migración Completo para Café Yanaloma
-- Ejecutar este script en el SQL Editor de Supabase (https://supabase.com/dashboard)
-- para habilitar la Caja POS, la Partida Doble y el Inventariado de Empaques.

-- 1. Agregar columnas operativas y de caja chica a la tabla 'transacciones'
ALTER TABLE transacciones 
ADD COLUMN IF NOT EXISTS mesa TEXT,
ADD COLUMN IF NOT EXISTS hora TEXT,
ADD COLUMN IF NOT EXISTS responsable TEXT,
ADD COLUMN IF NOT EXISTS pago NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cambio NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS observacion TEXT;

-- 2. Agregar columnas para control de descuentos y tipos de pedido
ALTER TABLE transacciones
ADD COLUMN IF NOT EXISTS tipo_pedido TEXT DEFAULT 'SITIO', -- 'SITIO' o 'LLEVAR'
ADD COLUMN IF NOT EXISTS monto_descuento NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS motivo_descuento TEXT;

-- 3. Agregar columnas de Partida Doble (Código de cuenta DEBE y HABER) en 'transacciones'
ALTER TABLE transacciones
ADD COLUMN IF NOT EXISTS codigo_debe TEXT,
ADD COLUMN IF NOT EXISTS codigo_haber TEXT;

-- Comentarios documentales en PostgreSQL
COMMENT ON COLUMN transacciones.mesa IS 'Mesa del cliente o indicador LLEVAR';
COMMENT ON COLUMN transacciones.hora IS 'Hora de la transacción (HH:MM)';
COMMENT ON COLUMN transacciones.responsable IS 'Personal a cargo del turno';
COMMENT ON COLUMN transacciones.pago IS 'Monto en efectivo recibido del cliente';
COMMENT ON COLUMN transacciones.cambio IS 'Cambio en efectivo devuelto al cliente';
COMMENT ON COLUMN transacciones.observacion IS 'Notas adicionales u observaciones de la transacción';
COMMENT ON COLUMN transacciones.tipo_pedido IS 'Tipo de pedido: SITIO (Para servir) o LLEVAR (Takeaway)';
COMMENT ON COLUMN transacciones.monto_descuento IS 'Descuento total aplicado en la transacción (Bs.)';
COMMENT ON COLUMN transacciones.motivo_descuento IS 'Motivo de la rebaja / justificación obligatoria';
COMMENT ON COLUMN transacciones.codigo_debe IS 'Código de la cuenta contable de destino (DEBE)';
COMMENT ON COLUMN transacciones.codigo_haber IS 'Código de la cuenta contable de origen (HABER)';

-- 4. Crear tabla de detalles de transacciones si no existiera
CREATE TABLE IF NOT EXISTS detalles_transaccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaccion_id BIGINT REFERENCES transacciones(id) ON DELETE CASCADE,
    producto_id BIGINT REFERENCES productos(id) ON DELETE SET NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario NUMERIC NOT NULL,
    subtotal NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Asegurar columna transaccion_id en libro_diario y configurar ON DELETE CASCADE
ALTER TABLE libro_diario
ADD COLUMN IF NOT EXISTS transaccion_id BIGINT;

ALTER TABLE libro_diario 
DROP CONSTRAINT IF EXISTS fk_libro_diario_transaccion;

ALTER TABLE libro_diario
ADD CONSTRAINT fk_libro_diario_transaccion 
FOREIGN KEY (transaccion_id) 
REFERENCES transacciones(id) 
ON DELETE CASCADE;

-- 6. Configurar políticas de RLS para detalles_transaccion (para evitar errores de violación de políticas)
ALTER TABLE detalles_transaccion DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir todo a anon en detalles_transaccion" ON detalles_transaccion;
CREATE POLICY "Permitir todo a anon en detalles_transaccion" 
ON detalles_transaccion 
FOR ALL 
TO public
USING (true) 
WITH CHECK (true);

-- 7. Recargar el caché de esquemas de PostgREST para aplicar cambios inmediatamente
NOTIFY pgrst, 'reload schema';
