-- Script de Migración para la Gestión de Usuarios
-- Ejecutar este script en el SQL Editor de Supabase (https://supabase.com/dashboard)

-- 1. Crear tabla de usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Contraseña del usuario (texto plano para facilidad de uso local)
    role TEXT NOT NULL CHECK (role IN ('admin', 'cajero', 'otro')),
    nombre TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Desactivar RLS para permitir accesos desde la app cliente de forma libre
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

-- 3. Insertar usuarios iniciales semilla
INSERT INTO usuarios (username, password, role, nombre)
VALUES 
('admin', 'admin123', 'admin', 'Administrador Yanaloma'),
('cajero', 'cajero123', 'cajero', 'Cajero de Turno'),
('otro', 'otro123', 'otro', 'Consultor Contable')
ON CONFLICT (username) 
DO UPDATE SET 
    nombre = EXCLUDED.nombre,
    role = EXCLUDED.role,
    password = EXCLUDED.password;

-- 4. Recargar el caché de esquemas de PostgREST
NOTIFY pgrst, 'reload schema';
